src/Soglasie/CommonBundle/Entity/Order.php
<?php

namespace Soglasie\CommonBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Order
 */
class Order
{
    const STATUS_CREATED = 0;
    const STATUS_PAID = 1;
    const STATUS_SENT = 2;

    static private $statuses = [
        self::STATUS_CREATED => 'Создана',
        self::STATUS_PAID => 'Оплачена',
        self::STATUS_SENT => 'Получена',
    ];

    static private $titles = [
        'Покупка кредитной истории с главной формы',
        'Покупка кредитной истории с формы акции',
        'Бесплатная консультация специалиста',
        'Получить бесплатную информацию',
        'Форма обратного звонка',
        'Покупка кредитной истории по цене 450 рублей',
        'Покупка кредитной истории по цене 700 рублей',
    ];

    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $amount;

    /**
     * @var integer
     */
    private $status;

    /**
     * @var \DateTime
     */
    private $created;

    /**
     * @var \JMS\Payment\CoreBundle\Entity\PaymentInstruction
     */
    private $paymentInstruction;

    /**
     * @var \Soglasie\UserBundle\Entity\User
     */
    private $user;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set amount
     *
     * @param string $amount
     * @return Order
     */
    public function setAmount($amount)
    {
        $this->amount = $amount;

        return $this;
    }

    /**
     * Get amount
     *
     * @return string 
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Set status
     *
     * @param integer $status
     * @return Order
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return integer 
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return Order
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime 
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set paymentInstruction
     *
     * @param \JMS\Payment\CoreBundle\Entity\PaymentInstruction $paymentInstruction
     * @return Order
     */
    public function setPaymentInstruction(\JMS\Payment\CoreBundle\Entity\PaymentInstruction $paymentInstruction = null)
    {
        $this->paymentInstruction = $paymentInstruction;

        return $this;
    }

    /**
     * Get paymentInstruction
     *
     * @return \JMS\Payment\CoreBundle\Entity\PaymentInstruction 
     */
    public function getPaymentInstruction()
    {
        return $this->paymentInstruction;
    }

    /**
     * Set user
     *
     * @param \Soglasie\UserBundle\Entity\User $user
     * @return Order
     */
    public function setUser(\Soglasie\UserBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \Soglasie\UserBundle\Entity\User 
     */
    public function getUser()
    {
        return $this->user;
    }
    /**
     * @var integer
     */
    private $type;


    /**
     * Set type
     *
     * @param integer $type
     * @return Order
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return integer 
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Get titles
     *
     * @return array
     */
    static public function getTitlesList()
    {
        return self::$titles;
    }
    
    /**
     * Get statuses
     *
     * @return array
     */
    static public function getStatusesList()
    {
        return self::$statuses;
    }

    public function __toString()
    {
        return (string) $this->id;
    }
    /**
     * @var \Soglasie\CommonBundle\Entity\OrderData
     */
    private $orderData;


    /**
     * Set orderData
     *
     * @param \Soglasie\CommonBundle\Entity\OrderData $orderData
     * @return Order
     */
    public function setOrderData(\Soglasie\CommonBundle\Entity\OrderData $orderData = null)
    {
        $this->orderData = $orderData;

        return $this;
    }

    /**
     * Get orderData
     *
     * @return \Soglasie\CommonBundle\Entity\OrderData 
     */
    public function getOrderData()
    {
        return $this->orderData;
    }
}

src/Soglasie/CommonBundle/Resources/views/Admin/edit.html.twig
{% extends 'SonataAdminBundle:CRUD:edit.html.twig' %}

{% block formactions %}
    <div class="well well-small form-actions">
        {% if app.request.isxmlhttprequest %}
            {% if admin.id(object) is not null %}
                <button type="submit" class="btn btn-success" name="btn_update">
                    <i class="fa fa-save"></i>
                    {{ 'btn_update'|trans({}, 'SonataAdminBundle') }}
                </button>
            {% else %}
                <button type="submit" class="btn btn-success" name="btn_create">
                    <i class="fa fa-plus-circle"></i>
                    {{ 'btn_create'|trans({}, 'SonataAdminBundle') }}
                </button>
            {% endif %}
        {% else %}
            {% if admin.supportsPreviewMode %}
                <button class="btn btn-info persist-preview" name="btn_preview" type="submit">
                    <i class="fa fa-eye"></i>
                    {{ 'btn_preview'|trans({}, 'SonataAdminBundle') }}
                </button>
            {% endif %}
            {% if admin.id(object) is not null %}
                <button type="submit" class="btn btn-success" name="btn_update_and_edit">
                    <i class="fa fa-save"></i>
                    {{ 'btn_update_and_edit_again'|trans({}, 'SonataAdminBundle') }}
                </button>

                {% if admin.hasroute('list') and admin.isGranted('LIST') %}
                    <button type="submit" class="btn btn-success" name="btn_update_and_list">
                        <i class="fa fa-save"></i> <i class="fa fa-list"></i>
                        {{ 'btn_update_and_return_to_list'|trans({}, 'SonataAdminBundle') }}
                    </button>
                {% endif %}

                {% if admin.hasroute('delete') and admin.isGranted('DELETE', object) %}
                    {{ 'delete_or'|trans({}, 'SonataAdminBundle') }}
                    <a class="btn btn-danger" href="{{ admin.generateObjectUrl('delete', object) }}">
                        <i class="fa fa-minus-circle"></i>
                        {{ 'link_delete'|trans({}, 'SonataAdminBundle') }}
                    </a>
                {% endif %}

                {% if admin.isAclEnabled() and admin.hasroute('acl') and admin.isGranted('MASTER', object) %}
                    <a class="btn btn-info" href="{{ admin.generateObjectUrl('acl', object) }}">
                        <i class="fa fa-users"></i>
                        {{ 'link_edit_acl'|trans({}, 'SonataAdminBundle') }}
                    </a>
                {% endif %}

                {% if constant('Soglasie\\CommonBundle\\Entity\\Order::STATUS_PAID') == object.status %}
                    <button type="submit" class="btn btn-success" name="btn_nbki">
                        <i class="fa fa-bar-chart-o"></i>
                        {{ 'sonata.btn.nbki'|trans({}, 'SonataAdminBundle') }}
                    </button>
                {% endif %}

                {% if constant('Soglasie\\CommonBundle\\Entity\\Order::STATUS_SENT') == object.status %}
                    <a class="btn btn-success" target="_blank" href="{{ admin.generateObjectUrl('data', object) }}">
                        <i class="fa fa-file-image-o"></i>
                        {{ 'sonata.btn.get_data'|trans({}, 'SonataAdminBundle') }}
                    </a>
                {% endif %}

            {% else %}
                {% if admin.hasroute('edit') and admin.isGranted('EDIT') %}
                    <button class="btn btn-success" type="submit" name="btn_create_and_edit">
                        <i class="fa fa-save"></i>
                        {{ 'btn_create_and_edit_again'|trans({}, 'SonataAdminBundle') }}
                    </button>
                {% endif %}
                {% if admin.hasroute('list') and admin.isGranted('LIST') %}
                    <button type="submit" class="btn btn-success" name="btn_create_and_list">
                        <i class="fa fa-save"></i> <i class="fa fa-list"></i>
                        {{ 'btn_create_and_return_to_list'|trans({}, 'SonataAdminBundle') }}
                    </button>
                {% endif %}
                <button class="btn btn-success" type="submit" name="btn_create_and_create">
                    <i class="fa fa-plus-circle"></i>
                    {{ 'btn_create_and_create_a_new_one'|trans({}, 'SonataAdminBundle') }}
                </button>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

src/Soglasie/CommonBundle/Resources/views/Admin/list__action_data.html.twig
{% if constant('Soglasie\\CommonBundle\\Entity\\Order::STATUS_SENT') == object.status %}
    <a class="btn btn-success" target="_blank" href="{{ admin.generateObjectUrl('data', object) }}">
        <i class="fa fa-file-image-o"></i>
        {{ 'sonata.btn.get_data'|trans({}, 'SonataAdminBundle') }}
    </a>
{% endif %}

src/Soglasie/CommonBundle/Resources/views/Admin/list__action_nbki.html.twig
{% if constant('Soglasie\\CommonBundle\\Entity\\Order::STATUS_PAID') == object.status %}
    <a class="btn btn-success" href="{{ admin.generateObjectUrl('edit', object) }}">
        <i class="fa fa-bar-chart-o"></i>
        {{ 'sonata.btn.nbki'|trans({}, 'SonataAdminBundle') }}
    </a>
{% endif %}

src/Soglasie/CommonBundle/Resources/views/Admin/list__action_pay.html.twig
{% if constant('Soglasie\\CommonBundle\\Entity\\Order::STATUS_CREATED') == object.status %}
<a class="btn btn-success" target="_blank" href="{{ path('payment_details', {id: object.id}) }}">
    <i class="fa fa-credit-card"></i>
    {{ 'sonata.btn.pay'|trans({}, 'SonataAdminBundle') }}
</a>
{% endif %}

src/Soglasie/CommonBundle/Resources/views/Admin/list__created.html.twig
<td>{{ object.created|localizeddate() }}</td>

src/Soglasie/CommonBundle/Resources/views/Admin/list__status.html.twig
<td>{{ object.statusesList[object.status] }}</td>